SELECT
	/* [QueryID][LNC002U_Sub09R.selectInspHist] */
	SEQ_NO AS SEQ_NO ,
	AGB_CD AS AGB_CD ,
	FN_USERNM(CRT_ID) AS CRT_ID ,
	FN_CDNM2('STQ',
	STQ_CD) AS STQ_NM ,
	CASE
		WHEN MTF_CD IS NULL THEN NVL(FN_CDNM2('STB', STB_CD), FN_CDNM2('STQ', STQ_CD))
		ELSE FN_CDNM2('MTF',
		MTF_CD)
	END AS STB_NM ,
	CRT_DTM AS REAL_CRT_DTM ,
	TO_CHAR(TO_DATE(CRT_DTM, 'YYYYMMDDHH24MISS'), 'YY-MM-DD HH24:MI') AS CRT_DTM ,
	APR_AMT / 10000 AS APR_AMT ,
	NEXT_USER_ID AS NEXT_USER_ID ,
	LTRIM(NVL(INSP_MEMO, AGENT_MEMO)) || ' ' || REPLACE(FN_REJCT_NM(REJCT_CD), '-') AS INSP_MEMO ,
	RECORD_NO AS RECORD_NO
FROM
	LNC005TH
WHERE
	INSP_NO = '20240514000385'
	AND AGB_CD IN ( '1', '2' )
	AND NVL(SMS_SEQNO, '0') = 0
	AND EDMS_FILE_ID IS NULL
ORDER BY
	CRT_DTM DESC