SELECT 'private ' || COL_TYPE || ' '|| COLUMN_NAME || '; ' || COMMENTS AS VO_STRING
  FROM (
SELECT LOWER(SUBSTR(REPLACE(INITCAP(A.COLUMN_NAME),'_'),1,1)) || SUBSTR(REPLACE(INITCAP(A.COLUMN_NAME),'_'),2,100) AS COLUMN_NAME
       ,CASE WHEN A.DATA_TYPE = 'NUMBER' AND A.DATA_SCALE = 0 THEN 'Long'
             WHEN A.DATA_TYPE = 'NUMBER' AND A.DATA_SCALE > 0 THEN 'Double'
             WHEN A.DATA_TYPE = 'DATE'                        THEN 'Timestamp'
                                                              ELSE 'String'
        END COL_TYPE
       ,CASE WHEN B.COMMENTS IS NULL THEN NULL
                                     ELSE '/* ' || B.COMMENTS || ' */'
         END COMMENTS
       ,A.COLUMN_ID
  FROM ALL_TAB_COLUMNS A
      ,ALL_COL_COMMENTS B
 WHERE A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME = B.COLUMN_NAME
   AND A.OWNER = 'BO_OWNER'
   AND A.TABLE_NAME = 'TAREA'
   AND A.COLUMN_NAME NOT IN ('INSERT_ID','INSERT_DATE','MODIFY_ID','MODIFY_DATE')
) 
ORDER BY COLUMN_ID
;

`

/*MyBatis INSERT Column Name List 持失*/
SELECT CASE WHEN COLUMN_ID = 1 THEN '  ' || COLUMN_NAME 
                               ELSE ', ' || COLUMN_NAME                            
        END COLUMN_NAME
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'BO_OWNER'
   AND TABLE_NAME = 'IF_LOTTERYPROMOCUST'
   AND COLUMN_NAME NOT IN ('INSERT_ID','INSERT_DATE','MODIFY_ID','MODIFY_DATE')   
ORDER BY COLUMN_ID;



/*MyBatis INSERT Parameter Column Name 持失*/
SELECT CASE WHEN COLUMN_ID = 1 THEN '  #{' || COLUMN_NAME || '}'
                               ELSE ', #{' || COLUMN_NAME || '}'
        END AS COLUMN_NAME
  FROM (
SELECT LOWER(SUBSTR(REPLACE(INITCAP(A.COLUMN_NAME),'_'),1,1)) || SUBSTR(REPLACE(INITCAP(A.COLUMN_NAME),'_'),2,100) AS COLUMN_NAME
     , A.COLUMN_ID
  FROM ALL_TAB_COLUMNS A
      ,ALL_COL_COMMENTS B
 WHERE A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME = B.COLUMN_NAME
   AND A.OWNER = 'BO_OWNER'
   AND A.TABLE_NAME = 'TLOTTERYPROMOPRIZE'
   AND A.COLUMN_NAME NOT IN ('INSERT_ID','INSERT_DATE','MODIFY_ID','MODIFY_DATE')
) 
ORDER BY COLUMN_ID


/*MyBatis UPDATE Parameter Column Name 持失*/
SELECT '     , ' || COLUMN_NAME || ' = #{' || PARAM_COLUMN_NAME || '}' 
  FROM (
SELECT LOWER(SUBSTR(REPLACE(INITCAP(A.COLUMN_NAME),'_'),1,1)) || SUBSTR(REPLACE(INITCAP(A.COLUMN_NAME),'_'),2,100) AS PARAM_COLUMN_NAME
     , A.COLUMN_NAME
     , A.COLUMN_ID
  FROM ALL_TAB_COLUMNS A
      ,ALL_COL_COMMENTS B
 WHERE A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME = B.COLUMN_NAME
   AND A.OWNER = 'BO_OWNER'
   AND A.TABLE_NAME = 'TLOTTERYPROMOPRIZE'
   AND A.COLUMN_NAME NOT IN ('INSERT_ID','INSERT_DATE','MODIFY_ID','MODIFY_DATE')
   AND A.COLUMN_NAME NOT IN (
 SELECT COLUMN_NAME
  FROM ALL_CONSTRAINTS A
      ,ALL_CONS_COLUMNS B
 WHERE A.OWNER = 'BO_OWNER'
   AND A.TABLE_NAME = 'TLOTTERYPROMOPRIZE'
   AND A.CONSTRAINT_TYPE = 'P'
   AND A.OWNER = B.OWNER
   AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME  
   )
   
) 
ORDER BY COLUMN_ID
;




SELECT COLUMN_NAME
  FROM ALL_CONSTRAINTS A
      ,ALL_CONS_COLUMNS B
 WHERE A.OWNER = 'BO_OWNER'
   AND A.TABLE_NAME = 'TLOTTERYPROMOPRIZE'
   AND A.CONSTRAINT_TYPE = 'P'
   AND A.OWNER = B.OWNER
   AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME  ;
  
  
  CREATE TABLE tddl (table_name varchar2(64), table_ddl varchar2(4000));
  INSERT INTO tddl SELECT 'TAREA',DBMS_METADATA.get_ddl ('TABLE', 'TAREA', 'BO_OWNER')  
  FROM sys.dual;
 COMMIT;
--UPDATE TDDL SET TABLE_DDL = REPLACE(TABLE_DDL,"'INSERT_ID' VARCHAR(50)",')
SELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(table_ddl,'"','`'),'BO_OWNER','shoppingnt'),'VARCHAR2','VARCHAR'),'ENABLE',''),'NVARCHAR','VARCHAR'),'NUMBER','INT'),'DATE','DATETIME'),'sysdate','CURRENT_TIMESTAMP') FROM tddl WHERE table_name = 'TAREA';

   