CREATE DEFINER=`root`@`localhost` FUNCTION `FN_CD_NM`( 
P_CD    VARCHAR(10) -- 코드
) RETURNS varchar(100) CHARSET utf8
    COMMENT '코드명 조회'
BEGIN
 DECLARE R_VAL VARCHAR(100);



    SELECT CD_NM INTO R_VAL FROM CM_CD WHERE CD = P_CD;



    RETURN R_VAL;

END