CREATE DEFINER=`root`@`localhost` FUNCTION `FN_SQ_NEXTVAL`(
P_SQ_ID varchar(100)
) RETURNS varchar(100) CHARSET utf8
    COMMENT '시퀀스 다음값 조회'
BEGIN
 DECLARE R_VAL BIGINT;

    UPDATE  SY_SQ
    SET     NEXT_VAL = LAST_INSERT_ID(NEXT_VAL + 1)
    WHERE   SQ_ID = P_SQ_ID;

    SELECT LAST_INSERT_ID() INTO R_VAL;

    RETURN R_VAL;
END