CREATE DEFINER=`root`@`localhost` FUNCTION `FN_SPLIT_STR`(
 X       VARCHAR(5000),

    DELIM   VARCHAR(12),

    POS INT
) RETURNS varchar(5000) CHARSET utf8
    COMMENT '구분자 순 문자열 출력'
BEGIN
 RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(X, DELIM, POS), LENGTH(SUBSTRING_INDEX(X, DELIM, POS - 1)) + 1), DELIM, '');
END