--초기 로드 테이블 순서
-- TBRAND, TGOODS, TGOODSADDINFO 
select * from information_schema.tables where upper(table_name) like upper('%bkup') order by table_name;

select count(*) from DP_TCATEGORY_BKUP;
ALTER TABLE DP_TCATEGORY RENAME TO DP_TCATEGORY_BK;
alter table DP_TCATEGORY_BKUP RENAME TO DP_TCATEGORY;
select count(*) from DP_TCATEGORY;

select count(*) from PD_TGOODS_BKUP;
ALTER TABLE PD_TGOODS RENAME TO PD_TGOODS_BK;
ALTER TABLE PD_TGOODS_BK DROP foreign key FK_PD_TBRAND_TO_PD_TGOODS;
ALTER TABLE PD_TGOODS_BKUP RENAME TO PD_TGOODS;
ALTER TABLE PD_TGOODS DROP foreign key FK_PD_TBRAND_TO_PD_TGOODSA;
ALTER TABLE PD_TGOODS ADD CONSTRAINT FK_PD_TBRAND_TO_PD_TGOODS FOREIGN KEY (`BRAND_CODE`) REFERENCES PD_TBRAND(`BRAND_CODE`);
select count(*) from PD_TGOODS;

select count(*) from PD_TGOODSDT_BKUP;
alter table PD_TGOODSDT rename to PD_TGOODSDT_BK;
alter table PD_TGOODSDT_BKUP rename to PD_TGOODSDT;
select count(*) from PD_TGOODSDT;

alter table PD_TGOODSADDINFO rename to PD_TGOODSADDINFO_BK;
alter table PD_TGOODSADDINFO_BK drop foreign key FK_PD_TGOODS_TO_PD_TGOODSADDINFO;
alter table PD_TGOODSADDINFO_BKUP rename to PD_TGOODSADDINFO;
ALTER TABLE PD_TGOODSADDINFO DROP foreign key FK_PD_TGOODS_TO_PD_TGOODSADDINFOA;
ALTER TABLE PD_TGOODSADDINFO ADD CONSTRAINT FK_PD_TGOODS_TO_PD_TGOODSADDINFO FOREIGN KEY (`GOODS_CODE`) REFERENCES PD_TGOODS(`GOODS_CODE`);


select count(*) from PD_TOFFER_BKUP;
alter table PD_TOFFER rename to PD_TOFFER_BK;
alter table PD_TOFFER_BKUP rename to PD_TOFFER;
select count(*) from PD_TOFFER;

select count(*) from MK_TPROMOM_BKUP;
ALTER TABLE MK_TPROMOM RENAME TO MK_TPROMOM_BK;
ALTER TABLE MK_TPROMOM_BK DROP foreign key FK_MK_TPROMOREFEAT_TO_MK_TPROMOM;
ALTER TABLE MK_TPROMOM_BKUP RENAME TO MK_TPROMOM;
ALTER TABLE MK_TPROMOM DROP foreign key FK_MK_TPROMOREFEAT_TO_MK_TPROMOMA;
ALTER TABLE MK_TPROMOM ADD CONSTRAINT FK_MK_TPROMOREFEAT_TO_MK_TPROMOM FOREIGN KEY (`REFEAT_NO`) REFERENCES MK_TPROMOREFEAT(`REFEAT_NO`);
select count(*) from MK_TPROMOM;

select count(*) from MK_TPROMOREFEAT_BKUP;
ALTER TABLE MK_TPROMOREFEAT RENAME TO MK_TPROMOREFEAT_BK;
ALTER TABLE MK_TPROMOREFEAT_BKUP RENAME TO MK_TPROMOREFEAT;
select count(*) from MK_TPROMOREFEAT;


select count(*) from DP_TCATEGORYGOODS_BKUP;
ALTER TABLE DP_TCATEGORYGOODS RENAME TO DP_TCATEGORYGOODS_BK;
ALTER TABLE DP_TCATEGORYGOODS_BKUP RENAME TO DP_TCATEGORYGOODS;
select count(*) from DP_TCATEGORYGOODS;

select count(*) from VD_TENTPUSER_BKUP;
ALTER TABLE VD_TENTPUSER RENAME TO VD_TENTPUSER_BK;
ALTER TABLE VD_TENTPUSER_BK DROP foreign key FK_VD_TENTERPRISE_TO_VD_TENTPUSER;

ALTER TABLE VD_TENTERPRISE RENAME TO VD_TENTERPRISE_BK;
ALTER TABLE VD_TENTERPRISE_BKUP RENAME TO VD_TENTERPRISE;

ALTER TABLE VD_TENTPUSER_BKUP RENAME TO VD_TENTPUSER;
ALTER TABLE VD_TENTPUSER DROP foreign key FK_VD_TENTERPRISE_TO_VD_TENTPUSERA;
ALTER TABLE VD_TENTPUSER ADD CONSTRAINT FK_VD_TENTERPRISE_TO_VD_TENTPUSER FOREIGN KEY (`ENTP_CODE`) REFERENCES VD_TENTERPRISE(`ENTP_CODE`);
select count(*) from VD_TENTPUSER;
SELECT COUNT(*) FROM VD_TENTERPRISE;

