---
- hosts: "{{ hostname }}"
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.pub
  gather_facts: false

  #usage (ubuntu) : ansible-playbook user_create.yaml -u ubuntu --ask-pass -c paramiko --become --ask-become-pass --extra-vars="hostname=192.168.176.131" -vvvv
  tasks:

    - name: Copy sudoers file for safety
      command: cp -f /etc/sudoers /etc/sudoers.tmp
      become: yes
      become_user: root

    - name: Create sudoers file backup
      command: cp -f /etc/sudoers /etc/sudoers.bak

    - name: Create admins group
      group: name=admins system=yes state=present

    - name: make sure we can sudo as admin group
      lineinfile: dest=/etc/sudoers.tmp state=present regexp='^%admins' line='%admins ALL=(ALL) NOPASSWD:ALL'

    - name: also make sure ssh-agent works via sudo
      lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

    - name: Adding Multiple Users and Appending in Sudoers file
      user:
       name: "{{ item }}"
       groups: admins
       append: yes
      with_items:
        - ansible

    - name: Set up authorized keys for the user
      authorized_key: user=ansible key="{{item}}"
      with_file:
        - /home/ansible/.ssh/id_rsa.pub

    - name: Final sudoers file check
      shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
