---
- hosts: all
  user: ansible
  become: True
  vars:
    domainname: exvarsinplay.netsec.kr
    backup: True
  vars_files:
    - vars/vars.yaml
  #usage: ansible-playbook -i ../hostsweb var_test.yaml
  tasks:
    - name: variable test
      vars:
        domainname: exvarsintasks.netsec.kr
      debug:
        msg: domainname is {{ domainname }}
    - name: Check if the backup_folder is set
      fail:
        msg: "The backup_folder needs to be set"
      when: backup_folder is not defined
    - name: Copy the crontab in tmp if the backup variable is true
      copy:
        src: /etc/crontab
        dest: "{{ backup_folder }}/crontab"
      when: backup
    - name: variable print
      debug:
        msg: crypt_ansible_become_pass is {{ crypt_ansible_become_pass }}
