- hosts: "{{ hostname }}"
  gather_facts: false
  become: true
  tasks:
    - name: create and/or change {{ username}}'s  password
      user:
        name: "{{ username }}"
        password: P@ssw0rd
