---
- hosts: webserver.yaml
  user: ansible
  become: True
  tasks:
    - name: Ensure apache is installed
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Ensure the apache service is started and enabled
      systemd:
        name: httpd
        state: started
        enabled: True
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Ensure apache is installed
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Ensure the apache service is started and enabled
      service:
        name: apache2
        state: started
        enabled: True
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

